Salesforce/src/objects/Achievement__c.object
<CustomObject>
    <fields>
        <fullName>Mission__c</fullName>
        <label>Mission</label>
        <referenceTo>Mission__c</referenceTo>
        <relationshipLabel>Achievements</relationshipLabel>
        <relationshipName>Achievements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Achievements</relationshipLabel>
        <relationshipName>Achievements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Achievement</label>
    <nameField>
        <displayFormat>ACHIEVEMENT{0000000}</displayFormat>
        <label>Achievement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/src/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/src/objects/Mission__c.object
<CustomObject>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>Missions</relationshipLabel>
        <relationshipName>Missions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Max_Point_Value__c</fullName>
        <label>Max Point Value</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mission_Start_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Mission Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mission_Type__c</fullName>
        <label>Mission Type</label>
        <picklist>
            <picklistValues>
                <fullName>Check-in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scanner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Mission</label>
    <nameField>
        <label>Mission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>Players</relationshipLabel>
        <relationshipName>Players</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Hunts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Player</label>
    <nameField>
        <displayFormat>PLAYER{000}</displayFormat>
        <label>Player Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/src/classes/MissionListControllerTests.cls
@IsTest
public class MissionListControllerTests {
    
    /* This basic test asserts that a list of missions with some completed 
       and some not completed is returned as expected. */
    static testmethod void getMissionListTest() {
        /* Initialize the custom Settings. */
        TestUtils.initSettings();
        
        /* Create the game */
        Game__c g = new Game__c(Name = 'TEST_GAME', End_Date_Time__c = Datetime.now().addDays(2));
        Database.insert(g);
        
        /* Create the player */
        Player__c p = TestUtils.createTestPlayer(g.id, TestConstants.USER_LICENSE_SALESFORCE);
        
        /* Create 3 missions */
        List<Mission__c> mList = new List<Mission__c>();
        for(Integer i=0;i<3;i++) {
            Mission__c m = new Mission__c(Name = 'TEST_MISSION_' + i, Mission_Type__c = 'Camera', Max_Point_Value__c = 100, Mission_Start_Time__c = Datetime.now().addHours(-12),Game__c = g.id);
            mList.add(m);
        }
        
        Database.insert(mList);
        
        /* Create an achievement for the first mission. */
        Achievement__c a = new Achievement__c(Mission__c = mList.get(0).id, player__c = p.id);
        Database.insert(a);
        
        ApexPages.PageReference pr = Page.MissionList;
        pr.getParameters().put('G',g.id);
        pr.getParameters().put('P',p.id);
        
        Test.setCurrentPage(pr);
        MissionListController c = new MissionListController();
        
        System.assertEquals(g.id,c.gameId,'Parameter G was not set to the game id in the controller.');
        System.assertEquals(p.id,c.playerID,'Parameter P was not set to the player id in the controller.');        
        
        List<MissionListController.Mission> missionList = new List<MissionListController.Mission>();
        /* Switch to run as the player */
        System.runAs(new User(Id = p.user__c)) {
            /* Invoke the completeCameraMissionType method */
            missionList = MissionListController.getMissionList(g.id);            
        }
        
        System.assertEquals(mList.size(), missionList.size(), 'Size of the list of Mission__c records did not match the size of the list of MissionController.Mission objects from the remote controller method.');
        for(MissionListController.Mission m:missionList) {
            if(a.Mission__c == m.mission.id) { System.assert(m.completed, 'Completed property on the MissionController.Mission object was not true for the completed mission. '); }
            else { System.assert(!m.completed, 'Completed property on the MissionControllerExtension.Mission object was true for an incompleted mission. ');}
        }
    }

}