Salesforce/src/objects/Achievement__c.object
<CustomObject>
    <fields>
        <fullName>Mission__c</fullName>
        <label>Mission</label>
        <referenceTo>Mission__c</referenceTo>
        <relationshipLabel>Achievements</relationshipLabel>
        <relationshipName>Achievements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Achievements</relationshipLabel>
        <relationshipName>Achievements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Achievement</label>
    <nameField>
        <displayFormat>ACHIEVEMENT{0000000}</displayFormat>
        <label>Achievement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/src/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <defaultValue>now() + 7</defaultValue>
        <label>Start Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/src/objects/Mission__c.object
<CustomObject>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>Missions</relationshipLabel>
        <relationshipName>Missions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Max_Point_Value__c</fullName>
        <label>Max Point Value</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mission_End_Time__c</fullName>
        <inlineHelpText>Optional end time for missions. Applies to all types. If null then mission end time is equivalent to game end time.</inlineHelpText>
        <label>Mission End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mission_Start_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Mission Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mission_Type__c</fullName>
        <label>Mission Type</label>
        <picklist>
            <picklistValues>
                <fullName>Check-in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scanner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to identify a user who you want to mention in a post of the hunt item</description>
        <label>Target User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Hunt_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mission</label>
    <nameField>
        <label>Mission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>Players</relationshipLabel>
        <relationshipName>Players</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Player</label>
    <nameField>
        <displayFormat>PLAYER{000}</displayFormat>
        <label>Player Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/src/classes/AchievementValidationTests.cls
@IsTest
public class AchievementValidationTests {
    /* There should never be more than one achievement record for a given user and a given mission. */
    static testmethod void duplicateAchievementPerInsertTest() {
    
        /* Initialize custom settings. */
        TestUtils.initSettings();
        
        /* Create a game */
        Game__c g = new Game__c(Name = 'TEST_GAME', Status__c = 'Active');
        Database.insert(g);
              
        /* Create a user for use as the target. */ 
        User u = TestUtils.createTestUserObject(TestConstants.USER_LICENSE_SALESFORCE);
        
        /* Create a mission */
        Mission__c m = new Mission__c(Target_User__c = u.id, Name = 'TEST_MISSION', Game__c = g.id, Max_Point_Value__c = 100, Mission_Type__c = TestConstants.MISSION_TYPE_SIGNATURE);
        Database.insert(M);
        
        /* Create a player */
        Player__c p = TestUtils.createTestPlayer(g.id,TestConstants.USER_LICENSE_SALESFORCE);
        
        Achievement__c a1 = new Achievement__c(player__c = p.id, mission__c = m.id);
        Achievement__c a2 = a1.clone();
        
        List<Achievement__c> aList = new List<Achievement__c>();
        aList.add(a1);
        aList.add(a2);
            
        try {
            Database.insert(aList);
            System.assert(false,'Rules should prevent two or more achievements being created with the same player and mission values.');
        } catch (System.DMLException e) {
            System.assertEquals(StatusCode.DUPLICATE_VALUE,e.getDMLType(0),'StatusCode on the DML Exception was not returned as expected.');
        }
    }
    
    static testmethod void oneAndOnlyOneAchievementTest() {
        /* Initialize custom settings. */
        TestUtils.initSettings();
        
        /* Create a game */
        Game__c g = new Game__c(Name = 'TEST_GAME', Status__c = 'Active');
        Database.insert(g);
        
        /* Create a user for use as the target. */ 
        User u = TestUtils.createTestUserObject(TestConstants.USER_LICENSE_SALESFORCE);
        
        /* Create a mission */
        Mission__c m = new Mission__c(Target_User__c = u.id, Name = 'TEST_MISSION', Game__c = g.id, Max_Point_Value__c = 100, Mission_Type__c = TestConstants.MISSION_TYPE_SIGNATURE);
        Database.insert(M);
        
        /* Create a player */
        Player__c p = TestUtils.createTestPlayer(g.id,TestConstants.USER_LICENSE_SALESFORCE);
        
        Achievement__c a1 = new Achievement__c(player__c = p.id, mission__c = m.id);
        Achievement__c a2 = a1.clone();
        Database.insert(a1);
        System.assert(a1.id != null, 'No ID means this insert failed.');
            
        try {
            Database.insert(a2);
            System.assert(false,'Rules should prevent a second achievement with the same player and mission values as an existing one from being created.');
        } catch (System.DMLException e) {
            System.assertEquals(StatusCode.DUPLICATE_VALUE,e.getDMLType(0),'StatusCode on the DML Exception was not returned as expected.');
        }
    }
    
    /* Achievements should not be create-able on for games that have ended. 
       for this validation testing the definition of "ended" is when the current
       time has passed the End_Date_Time__c value on the Game. */
    static testmethod void expiredGameTimeAchievementTest() {
        /* */
        /* Initialize custom settings. */
        TestUtils.initSettings();
        
        /* Create a game */
        Game__c g = new Game__c(Name = 'TEST_GAME', Status__c = 'Active', Start_Date_Time__c = DateTime.now().addDays(-2), End_Date_Time__c = DateTime.now().addMinutes(-5));
        Database.insert(g);
        
        /* Create a user for use as the target. */ 
        User u = TestUtils.createTestUserObject(TestConstants.USER_LICENSE_SALESFORCE);
        
        /* Create a mission */
        Mission__c m = new Mission__c(Target_User__c = u.id, Name = 'TEST_MISSION', Game__c = g.id, Max_Point_Value__c = 100, Mission_Type__c = TestConstants.MISSION_TYPE_SIGNATURE);
        Database.insert(M);
        
        /* Create a player */
        Player__c p = TestUtils.createTestPlayer(g.id,TestConstants.USER_LICENSE_SALESFORCE);
        
        /* Create the achievement on the mission related to the expired game. */
        Achievement__c a = new Achievement__c(player__c = p.id, mission__c = m.id);
        
        try{
            Database.insert(a);
            System.assert(false,'Insert of an Achievement__c record under an expired game should have failed.');
        } catch(System.DMLException e) {
            System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION, e.getDMLType(0),'StatusCode on the DML Exception was not returned as expected.');
        }
    }
    
    /* assert that a mission can not be completed after the mission end time has past. */
    static testmethod void expiredMissionTimeAchievementTest() {
        /* Initialize custom settings. */
        TestUtils.initSettings();
        
        /* Create a game */
        Game__c g = new Game__c(Name = 'TEST_GAME', Status__c = 'Active', Start_Date_Time__c = DateTime.now().addDays(-2), End_Date_Time__c = DateTime.now().addMinutes(-5));
        Database.insert(g);
        
        /* Create a user for use as the target. */ 
        User u = TestUtils.createTestUserObject(TestConstants.USER_LICENSE_SALESFORCE);
        
        /* Create a mission */
        Mission__c m = new Mission__c(Mission_Start_Time__c = Datetime.now().addDays(-3), Mission_End_Time__c = Datetime.now().addHours(-1),Target_User__c = u.id, Name = 'TEST_MISSION', Game__c = g.id, Max_Point_Value__c = 100, Mission_Type__c = TestConstants.MISSION_TYPE_SIGNATURE);
        Database.insert(M);
        
        /* Create a player */
        Player__c p = TestUtils.createTestPlayer(g.id,TestConstants.USER_LICENSE_SALESFORCE);
        
        /* Create the achievement on the mission related to the expired game. */
        Achievement__c a = new Achievement__c(player__c = p.id, mission__c = m.id);
        
        try{
            Database.insert(a);
            System.assert(false,'Insert of an Achievement__c record under an expired mission should have failed.');
        } catch(System.DMLException e) {
            System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION, e.getDMLType(0),'StatusCode on the DML Exception was not returned as expected.');
        }
    }
}