Salesforce/src/objects/Achievement__c.object
<CustomObject>
    <fields>
        <fullName>Mission__c</fullName>
        <label>Mission</label>
        <referenceTo>Mission__c</referenceTo>
        <relationshipLabel>Achievements</relationshipLabel>
        <relationshipName>Achievements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Achievements</relationshipLabel>
        <relationshipName>Achievements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Points_Awarded__c</fullName>
        <label>Points Awarded</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Achievement</label>
    <nameField>
        <displayFormat>ACHIEVEMENT{0000000}</displayFormat>
        <label>Achievement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/src/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/src/objects/Mission__c.object
<CustomObject>
    <fields>
        <fullName>Current_Point_Value__c</fullName>
        <description>Calculates the current value of the mission with a time-decay algorithm from the point the mission was started. The minimum value for any mission is 10% of the max points.</description>
        <formula>if( ( now() - Mission_Start_Time__c )*1440 &lt; 60, 1*Max_Point_Value__c, if( ( now() - Mission_Start_Time__c )*1440 &lt; 120, 0.9*Max_Point_Value__c, if( ( now() - Mission_Start_Time__c )*1440 &lt; 240, 0.75* Max_Point_Value__c, if( ( now() - Mission_Start_Time__c )*1440 &lt; 480, 0.6* Max_Point_Value__c, if( ( now() - Mission_Start_Time__c )*1440 &lt; 960, 0.5* Max_Point_Value__c, if( ( now() - Mission_Start_Time__c )*1440 &lt; 1440, 0.25* Max_Point_Value__c, 0.1* Max_Point_Value__c ))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Point Value</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>Missions</relationshipLabel>
        <relationshipName>Missions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Max_Point_Value__c</fullName>
        <label>Max Point Value</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mission_End_Time__c</fullName>
        <inlineHelpText>Optional end time for missions. Applies to all types. If null then mission end time is equivalent to game end time.</inlineHelpText>
        <label>Mission End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mission_Start_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Mission Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mission_Type__c</fullName>
        <label>Mission Type</label>
        <picklist>
            <picklistValues>
                <fullName>Check-in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scanner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Place__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Place</label>
        <referenceTo>Place__c</referenceTo>
        <relationshipLabel>Missions</relationshipLabel>
        <relationshipName>Hunt_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mission</label>
    <nameField>
        <label>Mission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/src/objects/Place__c.object
<CustomObject>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address2__c</fullName>
        <label>Address2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Place</label>
    <nameField>
        <label>Places Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Places</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>Players</relationshipLabel>
        <relationshipName>Players</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Hunts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Player</label>
    <nameField>
        <displayFormat>PLAYER{000}</displayFormat>
        <label>Player Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/src/classes/MissionListController.cls
public with sharing class MissionListController {

    public String gameId { get; set; }
    public String playerId { get; set; }
    public Boolean gameOver { get; set; }
    
    public class Mission{
        public Mission__c mission {get;set;}
        public boolean completed {get;set;}
        public Decimal pointsAwarded {get;set;}
        
        public Mission(Mission__c m){
            mission = m;
            completed = false;
        }
    }
    
    public MissionListController(){
        gameId = ApexPages.currentPage().getParameters().get('G');
        playerId = ApexPages.currentPage().getParameters().get('P');
        Game__c game = [SELECT End_date_Time__c FROM Game__c WHERE id = :gameId AND End_date_time__c > :datetime.now() ];
        if (game != null) {
            gameOver = false;
        } else {
            gameOver = true;
        }
        
    }

    @RemoteAction
    public static List<Mission> getMissionList(String gameId){
        List<Mission> missions = new List<Mission>();
        
        /* Secondary list to de-prioritize the completed missions. */
        List<Mission> completedMissions = new List<Mission>();
        
        Map<Id, Achievement__c> completedMissionAchievementIdMap = new Map<Id, Achievement__c>();
        
        /* TODO: condense the Achivement and Mission queries into one. */
        for (Achievement__c a : [SELECT Mission__c, Points_Awarded__c
                                   FROM Achievement__c 
                                  WHERE Player__r.Game__c = :gameId AND
                                        Player__r.User__c = :UserInfo.getUserId()]) {
            completedMissionAchievementIdMap.put(a.Mission__c, a);
        }
        
        /* Added filter for completed missions based on end datetime.*/
        for (Mission__c m : [SELECT Id, Description__c, Name, Current_Point_Value__c, Max_Point_Value__c, 
                                    Place__r.Location__Latitude__s, Place__r.Location__Longitude__s, Place__r.Address1__c, Place__r.Address2__c,
                                    Mission_Start_Time__c, Mission_Type__c
                               FROM Mission__c 
                              WHERE Mission_Start_Time__c < :datetime.now() AND 
                                    (Mission_End_Time__c > :datetime.now() OR
                                     Mission_End_Time__c = null) AND
                                    Game__c = :gameId 
                           ORDER BY Current_Point_Value__c DESC ]){
            Mission mission = new Mission(m);
            if (completedMissionAchievementIdMap.containsKey(m.Id)){
                mission.completed = true;
                mission.pointsAwarded = completedMissionAchievementIdMap.get(m.Id).Points_Awarded__c;
                completedMissions.add(mission);
            } else {
                missions.add(mission);
            }                               
        }
        
        /* Add all the completed missions to the end of the list. */
        missions.addAll(completedMissions);
        return missions;
    }    
}