Salesforce/src/objects/Achievement__c.object
<CustomObject>
    <fields>
        <fullName>Image_ID__c</fullName>
        <label>Image ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mission__c</fullName>
        <label>Mission</label>
        <referenceTo>Mission__c</referenceTo>
        <relationshipLabel>Achievements</relationshipLabel>
        <relationshipName>Achievements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Achievements</relationshipLabel>
        <relationshipName>Achievements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Points_Awarded__c</fullName>
        <label>Points Awarded</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Achievement</label>
    <nameField>
        <displayFormat>ACHIEVEMENT{0000000}</displayFormat>
        <label>Achievement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/src/objects/Cloud_Hunter_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>General Settings for the Cloud Hunter Application.</description>
    <fields>
        <fullName>Integration_Class_Name__c</fullName>
        <description>The name of the Apex class that implements the IntegrationIface interface.  This is an abstraction that allows the application to be installed into an org or optionally in a separate org while still supporting chatter and user integration.</description>
        <label>Integration Class Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Cloud Hunter Settings</label>
</CustomObject>

Salesforce/src/objects/Game__c.object
<CustomObject>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/src/objects/Mission__c.object
<CustomObject>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>Missions</relationshipLabel>
        <relationshipName>Missions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Non_User_Validation_Code__c</fullName>
        <label>Non User Validation Code</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Place__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Place</label>
        <referenceTo>Place__c</referenceTo>
        <relationshipLabel>Missions</relationshipLabel>
        <relationshipName>Hunt_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to identify a user who you want to mention in a post of the hunt item</description>
        <label>Target User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Hunt_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mission</label>
    <nameField>
        <label>Mission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/src/objects/Place__c.object
<CustomObject>
    <fields>
        <fullName>Distance_Tolerance__c</fullName>
        <description>Amount of tolerance from the place centroid is a user allowed to check-in.  This value is in METERS.</description>
        <label>Distance Tolerance (meters)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <required>true</required>
        <scale>5</scale>
        <type>Location</type>
    </fields>
    <label>Place</label>
    <nameField>
        <label>Places Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Places</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>Players</relationshipLabel>
        <relationshipName>Players</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Hunts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Player</label>
    <nameField>
        <displayFormat>PLAYER{000}</displayFormat>
        <label>Player Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>QR_Code__c</fullName>
        <label>QR Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

Salesforce/src/classes/MissionControllerExtension.cls
public with sharing class MissionControllerExtension {

    public String gameId { get; set; }
    public String playerId { get; set; }
  
    public MissionControllerExtension(ApexPages.StandardController stdController){
        gameId = ApexPages.currentPage().getParameters().get('G');
        playerId = ApexPages.currentPage().getParameters().get('P');
    }

    /* The PhoneGap JS libraries depend on the target OS - Android vs iOS. 
	   In this function, we determine the mobile platform that is invoking
	   this VF page via the 'User-Agent' HTTP header and then dynamically 
	   inject the platform appropriate JS file using VF Dynamic Components.
	*/
    public Component.Apex.IncludeScript getPhoneGapJS() {
        String userAgent = System.currentPageReference().getHeaders().get('User-Agent');
        Component.Apex.IncludeScript jsScript; 
        if (userAgent.contains('iPhone') || userAgent.contains('iPad')){
            jsScript = new Component.Apex.IncludeScript();
            jsScript.expressions.value = '{!URLFOR($Resource.PhoneGap1_8_1_iOS)}';
        }else if (userAgent.contains('Android')){
            jsScript = new Component.Apex.IncludeScript();
            jsScript.expressions.value = '{!URLFOR($Resource.PhoneGap1_8_1_Android)}';
        }        
        return jsScript;
    }
    
    /* The PhoneGap JS library for the Bar Code scanning plugin depend on the target OS - Android vs iOS. 
	   In this function, we determine the mobile platform that is invoking
	   this VF page via the 'User-Agent' HTTP header and then dynamically 
	   inject the platform appropriate JS file using VF Dynamic Components.
	*/
    public Component.Apex.IncludeScript getBarCodeScannerJS() {
        String userAgent = System.currentPageReference().getHeaders().get('User-Agent');
        Component.Apex.IncludeScript jsScript; 
        if (userAgent.contains('iPhone') || userAgent.contains('iPad')){
            jsScript = new Component.Apex.IncludeScript();
            jsScript.expressions.value = '{!URLFOR($Resource.BarCodeScanneriOS)}';
        }else if (userAgent.contains('Android')){
            jsScript = new Component.Apex.IncludeScript();
            jsScript.expressions.value = '{!URLFOR($Resource.BarCodeScannerAndroid)}';
        }        
        return jsScript;
    }

    /*JS Remoting function invoked from the VF page to complete a Camera type Mission*/
    @RemoteAction
    public static Decimal completeCameraMissionType(String imageData, String missionId, String gameId) {
        Mission__c mission = [select target_user__c, target_user__r.name from Mission__c where id = :missionId limit 1];
        //Create a new Achievement record for the Player.
        Achievement__c completedMission = completeMission(gameId, missionId);
        
        //Add the picture as an Attachment to the Achievement record
        Attachment a = new Attachment (ParentId = completedMission.Id,
                                       Body = EncodingUtil.base64Decode(imageData),
                                       ContentType = 'image/jpg',
                                       Name = 'PhoneImage');
        insert a;
        completedMission.image_Id__c = a.Id;
        update completedMission;
        
        /*Post the Achievement to Chatter. If the Mission has a Target User, the update will be posted to the Target User's Chatter feed.
		 Otherwise, it will be posted to the Player's Chatter feed.
		*/
        List<String> argList = new List<String>();
        argList.add(completedMission.Mission__r.Name);
        argList.add(String.valueOf(completedMission.Points_Awarded__c.intValue()));
        argList.add(mission.target_user__r.name);
        if (mission.target_user__c != null){
            postAchievement2Chatter(String.format(Label.PostMessage_Camera_User,argList), mission.target_user__c, EncodingUtil.base64Decode(imageData), 'PhoneImage.png');            
        }else {
            postAchievement2Chatter(String.format(Label.PostMessage_Camera,argList), UserInfo.getUserId(), EncodingUtil.base64Decode(imageData), 'PhoneImage.png');
        }
        return completedMission.Points_Awarded__c;
    }

    /*JS Remoting function invoked from the VF page to complete a Scan type Mission*/
    @RemoteAction
    public static Decimal completeScanMissionType(String scannedCode, String missionId, String gameId) {
        Mission__c mission = [select target_user__c, target_user__r.name, target_user__r.qr_code__c, Non_User_Validation_Code__c from Mission__c where id = :missionId limit 1];
        
        /*If the Mission has a Target User set, then the scanned QR/Bar Code has to match the value
		 of the QR_Code__c field on the Target User record.*/
        if (mission.target_user__r != null && mission.target_user__r.qr_code__c != null){
            if (scannedCode == mission.target_user__r.qr_code__c) {
                //Create a new Achievement record for the Player.
                Achievement__c completedMission = completeMission(gameId, missionId);
                if (completedMission.Points_Awarded__c != null) {
                    List<String> argList = new List<String>();
                    argList.add(completedMission.Mission__r.Name);
                    argList.add(String.valueOf(completedMission.Points_Awarded__c.intValue()));
                    argList.add(mission.target_user__r.name);
                    
                    //Post the Achievement to Target Usre's Chatter Feed. 
                    postAchievement2Chatter(String.format(Label.PostMessage_Scan_User,argList),mission.target_user__c, null, null);
                    return completedMission.Points_Awarded__c;
                } else {
                    System.debug('Error Point Value:'+completedMission.Points_Awarded__c);
                    return -1;
                }
            } else {
                //Scanned value does not match the Target User's QR Code. Mission failed.
                return -1;
            }
        } else {
            /*The Mission does not have a Target User. Instead, the scanned code has to match the value of 
			  the Non_User_Validation_Code__c field on the Mission record*/
            if (mission.Non_User_Validation_Code__c != null) {
               if (scannedCode == mission.Non_User_Validation_Code__c ){
                    Achievement__c completedMission = completeMission(gameId, missionId);
                    if (completedMission.Points_Awarded__c != null) {
                        
                        List<String> argList = new List<String>();
                        argList.add(completedMission.Mission__r.Name);
                        argList.add(String.valueOf(completedMission.Points_Awarded__c.intValue()));
                        argList.add(mission.target_user__r.name);
                        System.debug('Point Value:'+completedMission.Points_Awarded__c.intValue());
                        postAchievement2Chatter(String.format(Label.PostMessage_Scan,argList),UserInfo.getUserId(), null, null);
                        return completedMission.Points_Awarded__c;
                    } else {
                        System.debug('Error Point Value:'+completedMission.Points_Awarded__c);
                        return -1;
                    }
               } else {
                   	//Scanned value does not match the Non_User_Validation_Code__c value. Mission failed. 
                    return -1;
               }
            }
            return -1;
        }
    }

    /*JS Remoting function invoked from the VF page to complete a Check-in type Mission*/
    @RemoteAction
    public static Decimal completeCheckInMissionType(Decimal lat, Decimal lon, String missionId, String game) {
        System.debug(Logginglevel.INFO, 'Current location:'+lat+','+lon);
        /*Check-in type Missions have to have an associated Place record. The Place custom object uses the new
		Winter '13 Geo-location feature to geocode (i.e. lat/long) the location of the expected check-in point. The
		Distance_Tolerance__c field on the Place object captures how proximity radius of a successful check-in*/
        Mission__c mission = [select place__c, place__r.Distance_Tolerance__c, place__r.Location__latitude__s, 
                              place__r.Location__longitude__s, place__r.name from Mission__c where id = :missionId limit 1];

        System.debug(Logginglevel.INFO, 'Place location:'+mission.place__r.Location__latitude__s+','+mission.place__r.Location__longitude__s);
        if (mission.place__r != null && mission.place__r.Location__latitude__s != null){
            /*Using the new DISTANCE and GEOLOCATION functions in SOQL, determine if the user's current co-ordinates are within
			  an acceptable distance (i.e. Distance_Tolerance__c) of the Check-in location.*/
            String soql = 'select id from Place__c '+
                          'where DISTANCE(Location__c, GEOLOCATION('+lat+','+lon+'), \'km\') <' + mission.place__r.Distance_Tolerance__c/1000 +
                          ' and id=\''+mission.place__c+'\'';
            List<Place__c> nearbyPlaces = Database.query(soql);
            if (nearbyPlaces.size() == 1){
                Achievement__c completedMission = completeMission(game, missionId);
                List<String> argList = new List<String>();
                argList.add(completedMission.Mission__r.Name);
                argList.add(String.valueOf(completedMission.Points_Awarded__c.intValue()));
                argList.add(mission.place__r.name);

                postAchievement2Chatter(String.format(Label.PostMessage_Check_in,argList),
                                        UserInfo.getUserId(), null, null);
                return completedMission.Points_Awarded__c;
            }
            else{
                return -1;
            }
        }        
        return -1;
    }
    
    /*JS Remoting function invoked from the VF page to complete a Signature type Mission. The captures signature
	is passed to this function as a Base64 encoded SVG image.*/
    @RemoteAction
    public static Decimal completeSignatureMissionType(String signature, String missionId, String gameId) {
        System.debug(Logginglevel.INFO, 'Mission ID:'+missionId);
        System.debug(Logginglevel.INFO, 'Game ID:'+gameId);
        System.debug(Logginglevel.INFO, 'Signature:'+signature);
        Mission__c mission = [select target_user__c, target_user__r.name from Mission__c where id = :missionId limit 1];
        System.debug(Logginglevel.INFO, mission.target_user__c);
        Achievement__c completedMission = completeMission(gameId, missionId);
        Attachment a = new Attachment (ParentId = completedMission.Id,
                                       Body = EncodingUtil.base64Decode(signature),
                                       ContentType = 'image/svg+xml;base64',
                                       Name = 'SignatureImage');
        Database.insert(a);
        completedMission.image_Id__c = a.Id;
        Database.update(completedMission);
        
        List<String> argList = new List<String>();
        argList.add(completedMission.Mission__r.Name);
        argList.add(String.valueOf(completedMission.Points_Awarded__c.intValue()));
        argList.add(mission.target_user__r.name);
        
        postAchievement2Chatter(String.format(Label.PostMessage_Signature_User,argList),mission.target_user__c, EncodingUtil.base64Decode(signature), 'SignatureImage.png');

        return completedMission.Points_Awarded__c;
    }
    
    private static Achievement__c completeMission(String gameId, String missionId){
        Id playerId = [select id from Player__c where User__c = :UserInfo.getUserId()
                       and Game__c = :gameId limit 1].Id;
        Achievement__c a = new Achievement__c(Player__c = playerId, Mission__c = missionId);
        Database.insert(a);
        a = [select id, Mission__r.Name, Player__c, Mission__c, Points_Awarded__c from Achievement__c where id=:a.Id limit 1];
        return a;
    }
    
    private static void postAchievement2Chatter(String message, String userId, Blob file, String fileName){
        
        /* Check for a non-null custom setting value. */
        Cloud_Hunter_Settings__c c = Cloud_Hunter_Settings__c.getOrgDefaults();
        String className = c.Integration_Class_Name__c;
        if(className != null && !''.equals(className)) {
        
            //Get the Type corresponding to the class name 
            Type t = Type.forName(className);
        
            IntegrationIface connectionImpl = (IntegrationIface)t.newInstance();
            
            // post to the remote org.  
            connectionImpl.postToChatter(message, userId, file, fileName);
                
        } else {
    
            FeedItem fItem = new FeedItem();
            fItem.ParentId = userId; 
            fItem.Body = message; 
            if (file != null && fileName != null){
                fItem.Type = 'ContentPost'; 
                fItem.ContentFileName = fileName;
                fItem.ContentData = file;
                
            } else{
                fItem.Type = 'TextPost'; 
            }
            
            insert fItem; 
        }
    }
}