Salesforce/src/objects/Cloud_Hunter_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>General Settings for the Cloud Hunter Application.</description>
    <fields>
        <fullName>Integration_Class_Name__c</fullName>
        <description>The name of the Apex class that implements the IntegrationIface interface.  This is an abstraction that allows the application to be installed into an org or optionally in a separate org while still supporting chatter and user integration.</description>
        <label>Integration Class Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Cloud Hunter Settings</label>
</CustomObject>

Salesforce/src/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>Players</relationshipLabel>
        <relationshipName>Players</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Hunts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Player</label>
    <nameField>
        <displayFormat>PLAYER{000}</displayFormat>
        <label>Player Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/src/classes/GameListController.cls
public with sharing class GameListController {

    public List<Game__c> gameList { get; set; }
    public boolean activeGames { get; set; }
    
    public GameListController() {
        gameList = [select Id, Name, (Select Id from Players__r where user__c = :UserInfo.getUserId()) from Game__c where Status__c = 'Active' ];
        if (gameList.isEmpty()) {
            activeGames = false;
        } else {
            activeGames = true;
        }
    }

  @RemoteAction
  public static String checkPlayerRecord(String gameId){
      List<Player__c> playerList = [select Id from Player__c where User__c = :UserInfo.getUserId() and Game__c = :gameId LIMIT 1];
      if (playerList.size() == 0) {
          Player__c player = new Player__c(Game__c = gameId, User__c = UserInfo.getUserId());
          insert player;
          return player.id;
      } else {
          return playerList[0].id;
      }
  }

  public PageReference redirectForSingleGame() {
      /* initialize the connection if the configuration dictates.*/
      GameListController.invokeCustomImpl();
      
      /* Check the # active games. If exactly 1, make sure the user has a player. */
      if (gameList.size() == 1) {
          Game__c g = gameList.get(0);
          Id playerId;
          if (g.Players__r == null || g.Players__r.size() == 0) {
              Player__c p = new Player__c(Game__c = g.id, User__c = UserInfo.getUserId());
              Database.insert(p);
              playerId = p.id;
          } else {
              playerId = g.Players__r.get(0).id;
          }
          PageReference redirectPage = Page.Player;
          redirectPage.getParameters().put('id',playerId);
          redirectPage.getParameters().put('P',playerId);
          redirectPage.getParameters().put('G',g.id);
          redirectPage.setRedirect(true);
          return redirectPage;
          
      } else {
          /* TODO: Should the zero and more than one result cases be handled differently? */
          return null;
      }
  }
    
    private static void invokeCustomImpl() {
        /* Check for a non-null custom setting value. */
        Cloud_Hunter_Settings__c c = Cloud_Hunter_Settings__c.getOrgDefaults();
        String className = c.Integration_Class_Name__c;
        if(className != null && !''.equals(className)) {
        
            //Get the Type corresponding to the class name 
            Type t = Type.forName(className);
        
            IntegrationIface connectionImpl = (IntegrationIface)t.newInstance();
            
            // Call the methods that have a custom implementation 
            connectionImpl.initializeUser();                
        }
    }
}