Salesforce/src/objects/Facebook_Connection_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Contains settings for connection to Facebook for implementing the integration interface for photo and post</description>
    <fields>
        <fullName>Auth_Provider_Id__c</fullName>
        <label>Auth Provider Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auth_Provider_Name__c</fullName>
        <label>Auth Provider Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Initialized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Initialized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>My_Domain__c</fullName>
        <label>My Domain</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Facebook Connection Settings</label>
</CustomObject>

Salesforce/src/classes/IntegrationImpl.cls
public class IntegrationImpl implements IntegrationIface {
    
    /* Utilize */
    public Id initializeUser() {
        /* current user's id */
        Id userId = UserInfo.getUserId();
        
        /* Get the facebook access token */
        String token = Auth.AuthToken.getAccessToken(Facebook_Connection_Settings__c.getOrgDefaults().Auth_Provider_Id__c, Facebook_Connection_Settings__c.getOrgDefaults().Auth_Provider_Name__c);
        System.debug('token:'+token);
        System.debug('userid:'+userId);
        
        Facebook_Connection_Settings__c userSettings = Facebook_Connection_Settings__c.getValues(userId);	    
                
        /* copy the photos to the local org. If user not initialized.  */
        if(userSettings == null || !userSettings.Initialized__c ) {
            
            /* Get the photo from the urls in the remote user and copy to a file 
               in the local org. */
            String facebookPhotoUrl = 'https://graph.facebook.com/me/picture?type=large&access_token=';
            Id fileId = RemoteUtils.copyRemoteProfilePhoto(userId, facebookPhotoUrl, token);
            
            /* Finally callout to put the file on the profile in the local org. This 
               will be processed asynchronously because:
                    1) Prior methods invoked above establish transactions which block callouts
                    2) Chatter photo processing is asynchronous anyway. */
            RemoteUtils.createProfilePhoto(token, fileId, UserInfo.getSessionID(), Facebook_Connection_Settings__c.getOrgDefaults().My_Domain__c);
            
            return fileId;
        }       
        
        return null;
    }

    public void postToChatter(String message, String userId, Blob file, String fileName) {
        /*TODO: Initial implementation will not post to Facebook */
        //if(!Facebook_Connection_Settings__c.getOrgDefaults().Disable_Chatter_Posting__c) {
        //    RemoteUtils.postToChatter(message, userId, file, fileName);   
        //}
    }
}