Salesforce/src/objects/Game__c.object
<CustomObject>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/src/objects/Mission__c.object
<CustomObject>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>Missions</relationshipLabel>
        <relationshipName>Missions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Max_Point_Value__c</fullName>
        <label>Max Point Value</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mission_Start_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Mission Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mission_Type__c</fullName>
        <label>Mission Type</label>
        <picklist>
            <picklistValues>
                <fullName>Check-in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scanner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Place__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Place</label>
        <referenceTo>Place__c</referenceTo>
        <relationshipLabel>Missions</relationshipLabel>
        <relationshipName>Hunt_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to identify a user who you want to mention in a post of the hunt item</description>
        <label>Target User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Hunt_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mission</label>
    <nameField>
        <label>Mission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/src/objects/Place__c.object
<CustomObject>
    <label>Place</label>
    <nameField>
        <label>Places Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Places</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/src/classes/MissionValidationTests.cls
/* These tests assure the proper logic is enforced on the various mission types. */
@IsTest
public class MissionValidationTests {

    /* Scanner type missions should always have a target_user__c and the 
       related user should have a non-null qrcode field value. */
    static testmethod void scannerTypeValidationTest() {
        /* Create the game */
        Game__c g = new Game__c(Name = 'TEST_GAME');
        Database.insert(g);
        
        /* Create a scanner type mission without a target user. */
        Mission__c m = new Mission__c(Name = 'TEST_MISSION', Mission_Type__c = TestConstants.MISSION_TYPE_SCANNER, Max_Point_Value__c = 100, Mission_Start_Time__c = Datetime.now().addHours(-12),Game__c = g.id);
        try{
            Database.insert(m);
            System.assert(false,'Insert of a new scanner mission succeeded without a target user value. This is required and needs to be enforced.');
        } catch(System.DMLException e) {
            System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION, e.getDMLType(0),'StatusCode on the DML Exception was not returned as expected.');
        }
        
        /* TODO: need to apply qrcode logic once confirmation on the approach is identified. -AW
        /* Get a profile for the specified licensetype. 
        Profile p = [SELECT Id FROM Profile WHERE UserLicense.name = :TestConstants.USER_LICENSE_SALESFORCE LIMIT 1]; 
        
        /* Create a user without a qrcode field value. 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', EmailEncodingKey='UTF-8', 
                          LastName='Testing', LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName=TestConstants.USER_NAME_FOR_TESTS);
        
        System.runAs(new User(Id = UserInfo.getUserId())) {
            Database.insert(u);
        }
        
        /* Update the mission record with the target user value 
           
        m.Target_User__c = u.id;
        try {
            Database.insert(m);
            System.assert(false,'Insert of a scanner mission succeeded with a target user value pointing to a user without a QR code value.');
        } catch(System.DMLException e) {
            System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION, e.getDMLType(0),'StatusCode on the DML Exception was not returned as expected.');
        }
        */
    }
    
    /* Signature type missions should always have a target_user__c */
    static testmethod void signatureTypeValidationTest() {
        /* Create the game */
        Game__c g = new Game__c(Name = 'TEST_GAME');
        Database.insert(g);
        
        /* Create a signature type mission without a target user. */
        Mission__c m = new Mission__c(Name = 'TEST_MISSION', Mission_Type__c = TestConstants.MISSION_TYPE_SIGNATURE, Max_Point_Value__c = 100, Mission_Start_Time__c = Datetime.now().addHours(-12),Game__c = g.id);
        try{
            Database.insert(m);
            System.assert(false,'Insert of a new signature mission succeeded without a target user value. This is required and needs to be enforced.');
        } catch(System.DMLException e) {
            System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION,e.getDMLType(0),'StatusCode on the DML Exception was not returned as expected.');
        }
    }
    
    /* Check-in type missions should always have a Place__c value. This is currently enforced
       by virtue of the look up field having a required attribute which also prevents 
       deletion of any place that has */
    static testmethod void checkinTypeValidationTest() { 
        /* Create the game */
        Game__c g = new Game__c(Name = 'TEST_GAME');
        Database.insert(g);
        
        /* Create a mission */
        Mission__c m = new Mission__c(Name = 'TEST_MISSION', Mission_Type__c = TestConstants.MISSION_TYPE_CHECKIN, Max_Point_Value__c = 100, Mission_Start_Time__c = Datetime.now().addHours(-12),Game__c = g.id);
        try {
            Database.insert(m);
            System.assert(false, 'Insert of a check-in mission succeeded without a specified place.');
        } catch(System.DMLException e) {
            System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION,e.getDMLType(0),'StatusCode on the DML Exception was not returned as expected.');
        }
    }
}