Salesforce/src/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_Remaining__c</fullName>
        <formula>IF( NOW() &lt; Start_Date_Time__c,&quot;The Game has not started&quot;,
TEXT(FLOOR(End_Date_Time__c - now())) &amp; &quot; Days: &quot; &amp;
TEXT(FLOOR(((End_Date_Time__c - now()) - FLOOR(End_Date_Time__c - now())) * 24)) &amp; &quot; Hrs: &quot; &amp;
IF(
	FLOOR(End_Date_Time__c - now()) &gt; 0,
	TEXT(ROUND((((MOD(((End_Date_Time__c - now()) - (FLOOR(End_Date_Time__c - now()))) , (FLOOR(End_Date_Time__c - now()))) * 24) - (FLOOR(((End_Date_Time__c - now()) - (FLOOR(End_Date_Time__c - now()))) * 24))) * 60),0)) &amp; &quot; Mins&quot;,
	TEXT(ROUND((((MOD(((End_Date_Time__c - now()) - (FLOOR(End_Date_Time__c - now()))) , 1) * 24) - (FLOOR(((End_Date_Time__c - now()) - (FLOOR(End_Date_Time__c - now()))) * 24))) * 60),0)) &amp; &quot; Mins&quot;)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Time Remaining</label>
        <type>Text</type>
    </fields>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>Players</relationshipLabel>
        <relationshipName>Players</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Points_Awarded__c</fullName>
        <label>Total Points Awarded</label>
        <summarizedField>Achievement__c.Points_Awarded__c</summarizedField>
        <summaryForeignKey>Achievement__c.Player__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Hunts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Player</label>
    <nameField>
        <displayFormat>PLAYER{000}</displayFormat>
        <label>Player Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/src/classes/StandingsController.cls
public class StandingsController {

    public List<Player__c> standingsList { get; set; }
    public String gameId { get; set; }
    public String remainingTime { get; set; }
    public Game__c game { get; set; }
    
    public StandingsController() {
        gameId = ApexPages.currentPage().getParameters().get('G');
        standingsList = new List<Player__c>([select Total_Points_Awarded__c, User__r.Name, User__r.CompanyName, User__r.FullPhotoUrl, Game__r.Time_Remaining__c, Game__r.End_Date_Time__c from Player__c where Game__c = :gameId ORDER BY Total_Points_Awarded__c DESC limit 20 ]);
        game = standingsList.get(0).Game__r;
        remainingTime = game.Time_Remaining__c;
    }
}