Salesforce/src/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>Players</relationshipLabel>
        <relationshipName>Players</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Player</label>
    <nameField>
        <displayFormat>PLAYER{000}</displayFormat>
        <label>Player Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/src/classes/StandingsControllerTests.cls
@IsTest
public class StandingsControllerTests {
    
    static testmethod void basicInstanceTest() {
        /* Initialize the custom Settings. */
        TestUtils.initSettings();
        
        /* Create the game */
        Game__c g = new Game__c(Name = 'TEST_GAME', Status__c = 'Active');
        Database.insert(g);
        
        List<Player__c> pList = TestUtils.createTestPlayersForOneGame(g.id, 20, TestConstants.USER_LICENSE_SALESFORCE);
        
        PageReference p = Page.Standings;
        p.getParameters().put('G',g.id);
        Test.setCurrentPageReference(p);        
        
        StandingsController con = new StandingsController();
        
        System.assertEquals(pList.size(), con.standingsList.size(),'The size of players created for the game did not equal the standingslist from the controller.');
        
    }

}