Salesforce/src/objects/Game__c.object
<CustomObject>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/src/objects/Mission__c.object
<CustomObject>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>Missions</relationshipLabel>
        <relationshipName>Missions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Max_Point_Value__c</fullName>
        <label>Max Point Value</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mission_Start_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Mission Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mission_Type__c</fullName>
        <label>Mission Type</label>
        <picklist>
            <picklistValues>
                <fullName>Check-in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scanner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Place__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Place</label>
        <referenceTo>Place__c</referenceTo>
        <relationshipLabel>Missions</relationshipLabel>
        <relationshipName>Hunt_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mission</label>
    <nameField>
        <label>Mission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/src/objects/Place__c.object
<CustomObject>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distance_Tolerance__c</fullName>
        <description>Amount of tolerance from the place centroid is a user allowed to check-in.  This value is in METERS.</description>
        <label>Distance Tolerance (meters)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Place</label>
    <nameField>
        <label>Places Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Places</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/src/classes/PlaceValidationTests.cls
/* Test methods for validation of Place records. */
@IsTest
public class PlaceValidationTests {
    
    /* Deletion of a place must be blocked until all check-in missions are either changed
       to have a different type or are also removed. */
    static testmethod void placeDeleteTest() {
        List<SObject> insertList = new List<SObject>();
        
        /* Create a game */
        Game__c g = new Game__c(Name = 'TEST_GAME');
        insertList.add(g);
        
        /* Create a place */
        Place__c p = new Place__c(Name = 'TEST_PLACE', Location__Latitude__s = TestConstants.GEO_LATITUDE, 
                                   Location__Longitude__s = TestConstants.GEO_LONGITUDE, Distance_Tolerance__c = 100,
                                   Address1__c = '10 Main', Postal_Code__c = '00000');
        insertList.add(p);
        
        /* Insert the game and place. */
        Database.insert(insertList);
        
        /* Create a mission of type checkin  */
        Mission__c m = new Mission__c(Place__c = p.id, Name = 'TEST_MISSION', Mission_Type__c = TestConstants.MISSION_TYPE_CHECKIN, Max_Point_Value__c = 100, Mission_Start_Time__c = Datetime.now().addHours(-12),Game__c = g.id);
        Database.insert(m);
        
        /* Now try to delete the place. */
        try {
            Database.delete(p);
            System.assert(false, 'deletion of a place that is tied to a check-in mission succeeded. Check the deletion event handling defined on the lookup Mission__c.Place__c.');
        } catch(System.DMLException e) {
            System.assertEquals(StatusCode.DELETE_FAILED,e.getDMLType(0),'StatusCode on the DML Exception was not returned as expected. Enforcement expected here is from the flag on the Lookup field Mission__c.Place__c.');
        }
    }
}